server:
  port: 9422
spring:
  application:
    name: zipkin-server
  datasource:
    url: jdbc:mysql://192.168.177.128:3306/zipkin?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
zipkin:
   storage:
      type: mysql
eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://admin:admin@127.0.0.1:6868/eureka/ #,http://admin:admin@127.0.0.1:6869/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1 #指定IP地址
    instance-id: ${spring.application.name}:${server.port} #指定实例id