server:
  port: 6869 #服务端口

spring:
  application:
    name: microservice-config #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: https://github.com/eryeer/microserviceDemo-config.git
          username: eryeer
          password: 84512780zc
          search-paths: folder1 #搜索指定子文件夹
eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://admin:admin@127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ipAddress: 127.0.0.1