server:
  port: ${port:6868} #server port

spring:
  application:
    name: microservice-eureka #指定服务名

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    #serviceUrl:
      #defaultZone: http://admin:admin@127.0.0.1:6868/eureka/
  server:
    enable-self-preservation: true #开启自我保护模式

security:
  basic:
    enable: true #开启基于HTTP basic的认证
  user: #配置用户的账号信息
    name: admin
    password: admin