server:
  port: 6677 #服务端口
spring:
  application:
    name: microservice-gateway #指定服务名
zuul:
  routes:
    microservice-gateway:
      path: /microservice-gateway/**
      sensitiveHeaders:
      serviceId: microservice-gateway
    microservice-account: #microservice-account这个路由名字是任意写的
      path: /microservice-account/** #配置请求URL的请求规则
      sensitiveHeaders:
      serviceId: microservice-account #将/microservice-account/映射成serviceId对应的url，如http://localhost:8080
    microservice-iv:
      path: /microservice-iv/**
      sensitiveHeaders:
      serviceId: microservice-iv
eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://admin:admin@127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1 #指定IP地址
    instance-id: ${spring.application.name}:${server.port} #指定实例id